# Generated by Django 3.1.12 on 2022-10-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20221025_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='average_stars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
