# Generated by Django 3.1.12 on 2022-09-20 11:44

import django.core.validators
from django.db import migrations, models
import djongo.models.fields
import hotels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=8)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('stars', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('categories', djongo.models.fields.ArrayField(model_container=hotels.models.Category)),
                ('attributes', djongo.models.fields.EmbeddedField(model_container=hotels.models.Attributes, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('hotel_id', models.PositiveIntegerField()),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
    ]
