# Generated by Django 3.1.12 on 2022-10-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20221023_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
