# Generated by Django 3.1.12 on 2022-10-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20221023_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
