# Generated by Django 3.1.12 on 2022-10-28 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20221025_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 21, 21, 31, 868046)),
        ),
    ]
